name: Check

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  check:
    # Name the Job
    name: Lint and test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install back
        run: npm ci
        working-directory: ./back
      - name: Lint back
        run: npm run lint
        working-directory: ./back
      - name: Compile back
        run: npm run build
        working-directory: ./back
      - name: Dependency navigator
        run: npm run check-architecture
        working-directory: ./back
      - name: Install front
        run: npm ci
        working-directory: ./front
      - name: Lint front
        run: npm run lint
        working-directory: ./front
      - name: Compile front
        run: npm run build
        working-directory: ./front
