name: Deploy to Amazon ECS

on: [push]
#  release:
#    types: [ created ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: talan-bookadesk           # set this to your Amazon ECR repository name
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Push to ECR public
        id: build-and-push
        uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
        with:
          tags: |
            public.ecr.aws/t6p3t0v4/${{ steps.repoName.outputs.reponame }}:latest
            public.ecr.aws/t6p3t0v4/${{ steps.repoName.outputs.reponame }}:${{ steps.sha.outputs.sha7 }}
